import { describe, test, expect } from 'bun:test';
import { DreamEngine, stripAIFingerprints, humanizeCommitMessage, humanizeDiff } from '../src/agent/index.ts';
import { MemoryDatabase } from '../src/memory/database.ts';
import { createLLMClient } from '../src/llm/client.ts';
import type { KairosConfigOutput } from '../src/config/schema.ts';

describe('UNDERCOVER - stripAIFingerprints', () => {
  test('removes AI self-identification', () => {
    const input = 'As an AI, I have updated the code.';
    const result = stripAIFingerprints(input);
    expect(result).not.toContain('As an AI');
    expect(result).toContain('updated');
  });

  test('removes apologetic language', () => {
    const input = 'I apologize for the issue. Here is the fix.';
    const result = stripAIFingerprints(input);
    expect(result).not.toContain('apologize');
  });

  test('removes "Let me help" patterns', () => {
    const input = 'Let me help you fix this bug.';
    const result = stripAIFingerprints(input);
    expect(result).not.toContain('Let me help');
  });

  test('preserves non-AI content', () => {
    const input = 'Fixed the null pointer in main.ts line 42.';
    const result = stripAIFingerprints(input);
    expect(result).toContain('Fixed');
    expect(result).toContain('null pointer');
  });
});

describe('UNDERCOVER - humanizeCommitMessage', () => {
  test('adds conventional commit prefix', () => {
    const msg = humanizeCommitMessage('fixed the login bug');
    expect(msg).toMatch(/^(fix|feat|refactor|chore|docs|style|test|perf|build|ci)[:(]/);
  });

  test('strips AI fingerprints from commit', () => {
    const msg = humanizeCommitMessage('As an AI, I have updated the config file.');
    expect(msg).not.toContain('As an AI');
  });

  test('truncates long messages', () => {
    const long = 'a'.repeat(100);
    const msg = humanizeCommitMessage(long);
    expect(msg.length).toBeLessThanOrEqual(72);
  });

  test('keeps messages under 72 chars', () => {
    const msg = humanizeCommitMessage('fix: update auth module');
    expect(msg.length).toBeLessThanOrEqual(72);
  });
});

describe('UNDERCOVER - humanizeDiff', () => {
  test('removes AI-generated markers', () => {
    const diff = '+// Generated by GPT-4\n+const x = 1;';
    const result = humanizeDiff(diff);
    expect(result).not.toContain('Generated by');
    expect(result).toContain('const x = 1');
  });
});

describe('DreamEngine', () => {
  test('enforceTTL deletes old sessions', async () => {
    const db = new MemoryDatabase(':memory:');
    const oldDate = new Date(Date.now() - 100 * 24 * 60 * 60 * 1000).toISOString();
    db.insertSession({ id: 'old', title: 'Old', model: 'test', createdAt: oldDate, updatedAt: oldDate });
    db.insertSession({ id: 'new', title: 'New', model: 'test', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() });

    const config = { memory: { ttlDays: 30 } } as unknown as KairosConfigOutput;
    const llm = createLLMClient({ provider: 'llamacpp', model: 'test', baseUrl: 'http://localhost:8080' });
    const engine = new DreamEngine(db, llm, config);

    const deleted = await engine.enforceTTL();
    expect(deleted).toBe(1);
    expect(db.getSession('old')).toBeNull();
    expect(db.getSession('new')).not.toBeNull();
    db.close();
  });
});
