const AI_FINGERPRINTS = [
  /\b(as an ai|as a language model|as an assistant|i'm an ai|i am an ai)\b/gi,
  /\b(I apologize|I'm sorry|apologies)\b/gi,
  /\b(here's the|here is the) (updated|revised|modified) (code|version|implementation)\b/gi,
  /\b(Let me (help|assist|fix|update|rewrite))\b/gi,
  /\b(sure|of course|certainly|absolutely|definitely),?\s*(I|let me|here)\b/gi,
  /\b(I'll (help|assist|fix|update|rewrite|create|implement))\b/gi,
  /\b(based on (your|the) (request|instructions|requirements))\b/gi,
  /\b(I've (updated|fixed|modified|created|implemented|added))\b/gi,
];

const HUMAN_PATTERNS = [
  /\b(fix|refactor|update|add|remove|change|move)\b/gi,
  /\b(typo|bug|issue|error|problem)\b/gi,
  /\b(works?|done|good|nice|thanks?)\b/gi,
];

const COMMIT_PREFIXES = [
  'fix', 'feat', 'refactor', 'chore', 'docs', 'style', 'test', 'perf', 'build', 'ci',
];

export function stripAIFingerprints(text: string): string {
  let cleaned = text;
  for (const pattern of AI_FINGERPRINTS) {
    cleaned = cleaned.replace(pattern, '');
  }
  cleaned = cleaned.replace(/\s{2,}/g, ' ').trim();
  return cleaned;
}

export function humanizeCommitMessage(message: string): string {
  let cleaned = stripAIFingerprints(message);

  const prefix = COMMIT_PREFIXES[Math.floor(Math.random() * COMMIT_PREFIXES.length)] ?? 'chore';

  if (!cleaned.match(/^(fix|feat|refactor|chore|docs|style|test|perf|build|ci)[:(]/i)) {
    cleaned = `${prefix}: ${cleaned.charAt(0).toLowerCase()}${cleaned.slice(1)}`;
  }

  const sentences = cleaned.split(/[.!?]+/).filter((s) => s.trim());
  if (sentences.length > 1) {
    cleaned = sentences[0]?.trim() ?? cleaned;
  }

  if (cleaned.length > 72) {
    cleaned = cleaned.slice(0, 69) + '...';
  }

  return cleaned;
}

export function humanizeDiff(diff: string): string {
  return diff
    .replace(/Generated by .+/gi, '')
    .replace(/Auto-generated .+/gi, '')
    .replace(/\+\/\/ This (code|file|change) was (generated|created|written) by .+/gi, '')
    .trim();
}
