#!/usr/bin/env bun
/**
 * skill-creator/scripts/run.ts
 *
 * Scaffolds a new skill's standard folder structure and SKILL.md manifest.
 * Validates name and category before writing; validates the generated
 * manifest after writing. Does not register or execute anything.
 */

import { parseArgs } from "util";
import { existsSync, mkdirSync, writeFileSync, readFileSync } from "fs";
import { join } from "path";

const VALID_CATEGORIES = ["analysis", "automation", "code-generation", "deployment", "testing", "documentation"];
const NAME_RE = /^[a-z][a-z0-9-]*$/;

interface CreatorArgs {
  name: string;
  description: string;
  category: string;
  author: string;
  skillsDir: string;
  force: boolean;
}

function parseCliArgs(): CreatorArgs {
  const { values } = parseArgs({
    args: process.argv.slice(2),
    options: {
      name: { type: "string" },
      description: { type: "string" },
      category: { type: "string" },
      author: { type: "string", default: "harness-core" },
      "skills-dir": { type: "string", default: ".." },
      force: { type: "boolean", default: false },
    },
  });

  if (!values.name) {
    console.error("Error: --name is required");
    process.exit(1);
  }
  if (!NAME_RE.test(values.name as string)) {
    console.error(`Error: --name must match ${NAME_RE} (lowercase, hyphen-separated)`);
    process.exit(1);
  }
  if (!values.description) {
    console.error("Error: --description is required");
    process.exit(1);
  }
  if (!values.category || !VALID_CATEGORIES.includes(values.category as string)) {
    console.error(`Error: --category must be one of: ${VALID_CATEGORIES.join(", ")}`);
    process.exit(1);
  }

  return {
    name: values.name as string,
    description: values.description as string,
    category: values.category as string,
    author: (values.author as string) ?? "harness-core",
    skillsDir: (values["skills-dir"] as string) ?? "..",
    force: values.force as boolean,
  };
}

function renderManifest(args: CreatorArgs): string {
  return `---
name: "${args.name}"
version: "1.0.0"
description: "${args.description}"
author: "${args.author}"
category: "${args.category}"
tools:
  - read_file
permissions:
  - allow: [read_file]
  - ask: [write_file]
dependencies:
  bun: ">=1.1.0"
  packages: []
entrypoint: "scripts/run.ts"
---

## Purpose

TODO: describe what this skill does and why it exists, in 1-2 paragraphs.

## Behavior Patterns

- TODO: describe how the skill behaves, step by step.

## When to Use

- TODO: describe the situations where this skill should be invoked.
- TODO: describe situations where it should NOT be used instead.

## Example Invocations

\`\`\`
/skill run ${args.name} --example-arg value
\`\`\`

## Expected Inputs

- TODO: list CLI arguments with types and required/optional status.

## Expected Outputs

TODO: describe the output shape (JSON schema or file output).

## Side Effects and Warnings

- TODO: describe any writes, external calls, or risks.
`;
}

function renderRunStub(name: string): string {
  return `#!/usr/bin/env bun
/**
 * ${name}/scripts/run.ts
 *
 * TODO: implement this skill's actual logic. This is a placeholder
 * generated by skill-creator.
 */

import { parseArgs } from "util";

function main() {
  const { values } = parseArgs({
    args: process.argv.slice(2),
    options: {
      help: { type: "boolean", default: false },
    },
    strict: false,
  });

  if (values.help) {
    console.log("${name}: not yet implemented. See SKILL.md for the intended interface.");
    return;
  }

  console.error(JSON.stringify({ error: "not-implemented", message: "${name} has not been implemented yet. Edit scripts/run.ts." }, null, 2));
  process.exit(1);
}

main();
`;
}

function parseFrontmatter(content: string): Record<string, string> | null {
  const m = content.match(/^---\n([\s\S]*?)\n---/);
  if (!m) return null;
  const fields: Record<string, string> = {};
  for (const line of m[1].split("\n")) {
    const fm = line.match(/^(\w+):\s*"?([^"]*)"?\s*$/);
    if (fm) fields[fm[1]] = fm[2];
  }
  return fields;
}

function main() {
  const args = parseCliArgs();
  const skillPath = join(args.skillsDir, args.name);

  if (existsSync(skillPath) && !args.force) {
    console.error(JSON.stringify({ error: "skill-exists", message: `${skillPath} already exists. Use --force to overwrite.` }, null, 2));
    process.exit(1);
  }

  const dirs = ["scripts", "references", "config", "examples", "tests"];
  for (const d of dirs) {
    mkdirSync(join(skillPath, d), { recursive: true });
  }

  const filesCreated: string[] = [];

  const manifestPath = join(skillPath, "SKILL.md");
  writeFileSync(manifestPath, renderManifest(args), "utf-8");
  filesCreated.push(manifestPath);

  const runPath = join(skillPath, "scripts", "run.ts");
  writeFileSync(runPath, renderRunStub(args.name), "utf-8");
  filesCreated.push(runPath);

  const configPath = join(skillPath, "config", "defaults.yaml");
  writeFileSync(configPath, "# TODO: add configuration defaults\n", "utf-8");
  filesCreated.push(configPath);

  const refPath = join(skillPath, "references", "notes.md");
  writeFileSync(refPath, `# Reference Notes\n\nTODO: add reference material for ${args.name}.\n`, "utf-8");
  filesCreated.push(refPath);

  const inputPath = join(skillPath, "examples", "input.md");
  writeFileSync(inputPath, "TODO: add an example CLI invocation\n", "utf-8");
  filesCreated.push(inputPath);

  const outputPath = join(skillPath, "examples", "expected-output.md");
  writeFileSync(outputPath, "TODO: add the expected output for the example above\n", "utf-8");
  filesCreated.push(outputPath);

  const testPath = join(skillPath, "tests", "test_skill.sh");
  writeFileSync(testPath, `#!/usr/bin/env bash\n# TODO: write real tests for ${args.name}\nset -euo pipefail\necho "TODO: not yet implemented"\nexit 1\n`, "utf-8");
  filesCreated.push(testPath);

  // Validate the manifest we just wrote.
  const written = readFileSync(manifestPath, "utf-8");
  const fields = parseFrontmatter(written);
  const requiredFields = ["name", "version", "description", "author", "category", "entrypoint"];
  const manifestValid = !!fields && requiredFields.every((f) => fields[f] && fields[f].length > 0);

  console.log(JSON.stringify({ skillName: args.name, path: skillPath, filesCreated, manifestValid }, null, 2));
  if (!manifestValid) process.exit(1);
}

main();
